import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { z } from "zod";
const querySchema = z.object({ q: z.string().trim().min(2).max(120), type: z.enum(["all", "posts", "replies", "artifacts", "spaces", "people"]).default("all"), space: z.string().trim().max(80).optional(), author: z.string().trim().max(80).optional(), from: z.string().date().optional(), to: z.string().date().optional(), status: z.enum(["PUBLISHED", "COMMUNITY_REVIEWED", "VERIFIED"]).optional(), page: z.coerce.number().int().min(1).max(100).default(1) });
const limit = 10;
export async function GET(request: Request) {
  const parsed = querySchema.safeParse(Object.fromEntries(new URL(request.url).searchParams)); if (!parsed.success) return NextResponse.json({ error: "Search needs at least two characters.", issues: parsed.error.flatten() }, { status: 400 });
  const { q, type, space, author, from, to, status, page } = parsed.data; const session = await auth(); const userId = session?.user?.id; const blocked = userId ? await prisma.userBlock.findMany({ where: { blockerId: userId }, select: { blockedId: true } }) : []; const muted = userId ? await prisma.spaceMute.findMany({ where: { userId }, select: { spaceId: true } }) : []; const blockedIds = blocked.map((item) => item.blockedId); const mutedIds = muted.map((item) => item.spaceId); const text = { contains: q, mode: "insensitive" as const };
  const [posts, replies, artifacts, spaces, people] = await Promise.all([
    type === "all" || type === "posts" ? prisma.post.findMany({ where: { isDeleted: false, isDraft: false, visibility: "PUBLIC", ...(blockedIds.length ? { authorId: { notIn: blockedIds } } : {}), ...(mutedIds.length ? { spaceId: { notIn: mutedIds } } : {}), ...(space ? { space: { slug: space } } : {}), ...(author ? { author: { username: author } } : {}), ...(from || to ? { createdAt: { ...(from ? { gte: new Date(`${from}T00:00:00.000Z`) } : {}), ...(to ? { lte: new Date(`${to}T23:59:59.999Z`) } : {}) } } : {}), ...(parsed.data.type === "posts" ? { OR: [{ title: text }, { body: text }] } : { OR: [{ title: text }, { body: text }] }) }, include: { author: { select: { displayName: true, username: true } }, space: { select: { name: true, slug: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * limit, take: limit }) : [],
    type === "all" || type === "replies" ? prisma.reply.findMany({ where: { isDeleted: false, body: text, post: { isDeleted: false, isDraft: false, visibility: "PUBLIC", ...(space ? { space: { slug: space } } : {}), ...(author ? { author: { username: author } } : {}), ...(from || to ? { createdAt: { ...(from ? { gte: new Date(`${from}T00:00:00.000Z`) } : {}), ...(to ? { lte: new Date(`${to}T23:59:59.999Z`) } : {}) } } : {}) } }, include: { author: { select: { displayName: true, username: true } }, post: { select: { id: true, title: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * limit, take: limit }) : [],
    type === "all" || type === "artifacts" ? prisma.artifact.findMany({ where: { visibility: "PUBLIC", status: status ?? { in: ["PUBLISHED", "COMMUNITY_REVIEWED", "VERIFIED"] }, ...(space ? { space: { slug: space } } : {}), ...(author ? { author: { username: author } } : {}), ...(from || to ? { updatedAt: { ...(from ? { gte: new Date(`${from}T00:00:00.000Z`) } : {}), ...(to ? { lte: new Date(`${to}T23:59:59.999Z`) } : {}) } } : {}), OR: [{ title: text }, { summary: text }, { body: text }] }, include: { author: { select: { displayName: true, username: true } }, space: { select: { name: true, slug: true } } }, orderBy: { updatedAt: "desc" }, skip: (page - 1) * limit, take: limit }) : [],
    type === "all" || type === "spaces" ? prisma.space.findMany({ where: { isPublic: true, OR: [{ name: text }, { slug: text }, { description: text }] }, orderBy: { isFeatured: "desc" }, skip: (page - 1) * limit, take: limit }) : [],
    type === "all" || type === "people" ? prisma.user.findMany({ where: { profileVisibility: "PUBLIC", OR: [{ displayName: text }, { username: text }] }, select: { id: true, displayName: true, username: true, bio: true, avatarUrl: true }, orderBy: { displayName: "asc" }, skip: (page - 1) * limit, take: limit }) : [],
  ]);
  return NextResponse.json({ query: q, page, results: { posts, replies, artifacts, spaces, people }, filters: { type, space: space ?? null, author: author ?? null, from: from ?? null, to: to ?? null, status: status ?? null } });
}