import Link from "next/link";
import { notFound } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { ProductNav } from "@/components/product-nav";
import { SpaceMembership } from "@/components/space-membership";
import { PinDiscussionButton } from "@/components/pin-discussion-button";

export default async function SpacePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const session = await auth();
  const space = await prisma.space.findUnique({ where: { slug, isPublic: true }, include: { _count: { select: { members: true, posts: true } }, posts: { where: { isDeleted: false, isDraft: false }, orderBy: [{ isPinned: "desc" }, { createdAt: "desc" }], take: 12, include: { author: { select: { displayName: true, username: true } }, _count: { select: { replies: true } } } } } });
  if (!space) notFound();
  const [viewerMembership, members] = await Promise.all([session?.user?.id ? prisma.spaceMember.findUnique({ where: { userId_spaceId: { userId: session.user.id, spaceId: space.id } }, select: { isModerator: true } }) : null, prisma.spaceMember.findMany({ where: { spaceId: space.id }, orderBy: [{ isModerator: "desc" }, { joinedAt: "desc" }], take: 24, include: { user: { select: { displayName: true, username: true } } } })]);
  const moderators = members.filter((member) => member.isModerator); const pinnedPosts = space.posts.filter((post) => post.isPinned);
  const composerUrl = `/feed?space=${encodeURIComponent(space.slug)}&returnTo=${encodeURIComponent(`/spaces/${space.slug}`)}#composer`;
  return <main id="main-content" tabIndex={-1} className="app-shell"><ProductNav/><section className="surface-section space-detail"><header className="space-detail-header"><p className="eyebrow">{space.isFeatured ? "Featured Space" : "Space"}</p><h1>{space.name}</h1><p>{space.description}</p><div className="space-detail-actions"><SpaceMembership slug={space.slug} initialJoined={Boolean(viewerMembership)} initialMembers={space._count.members}/><Link className="button-outline" href={composerUrl}>Start a discussion in {space.name}</Link></div><p className="help">{space._count.members} members · {space._count.posts} discussions{viewerMembership?.isModerator ? " · You moderate this Space" : ""}</p></header><div className="space-detail-grid"><section>{pinnedPosts.length > 0 && <section className="space-pinned-panel" aria-labelledby="pinned-discussions"><p className="eyebrow">Pinned</p><h2 id="pinned-discussions">Start here</h2>{pinnedPosts.map((post) => <article key={post.id} className="panel"><h3><Link href={`/posts/${post.id}`}>{post.title}</Link></h3><p>{post.body.slice(0, 180)}{post.body.length > 180 ? "…" : ""}</p></article>)}</section>}<h2>Recent discussions</h2>{space.posts.length ? <div className="space-post-list">{space.posts.map((post) => <article key={post.id} className="panel"><span className="badge">{post.isPinned ? "pinned" : post.type.toLowerCase()}</span><h3><Link href={`/posts/${post.id}`}>{post.title}</Link></h3><p>{post.body.slice(0,220)}{post.body.length>220?"…":""}</p><footer><Link href={`/people/${post.author.username}`}>{post.author.displayName}</Link><Link href={`/posts/${post.id}#replies`}>{post._count.replies} replies</Link>{viewerMembership?.isModerator && <PinDiscussionButton slug={space.slug} postId={post.id} initialPinned={post.isPinned}/>}</footer></article>)}</div> : <div className="panel"><h3>No discussions yet.</h3><p className="help">Start the first conversation in {space.name}.</p></div>}<section className="space-members-panel"><h2>Members</h2>{members.length?<ul className="space-member-list">{members.map(member=><li key={member.user.username}><Link href={`/people/${member.user.username}`}>{member.user.displayName}</Link><span>{member.isModerator?"Moderator":"Member"}</span></li>)}</ul>:<p className="help">No members are visible yet.</p>}</section></section><aside className="space-detail-aside"><section className="panel"><h2>Rules</h2><p className="help">{space.rules||"Be constructive, share context, and respect other members."}</p></section><section className="panel"><h2>Topics</h2><div className="profile-tags">{space.tags.map(tag=><span key={tag}>{tag}</span>)}</div></section><section className="panel"><h2>Moderators</h2>{moderators.length?<ul className="space-member-list">{moderators.map(member=><li key={member.user.username}><Link href={`/people/${member.user.username}`}>{member.user.displayName}</Link></li>)}</ul>:<p className="help">No moderators are listed yet.</p>}</section></aside></div></section></main>;
}
