import Link from "next/link";
import { notFound } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { ProductNav } from "@/components/product-nav";
import { SpaceMembership } from "@/components/space-membership";

export default async function SpacePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const session = await auth(); const viewerId = session?.user?.id ?? "__anonymous__";
  const space = await prisma.space.findUnique({ where: { slug, isPublic: true }, include: { members: { where: { userId: viewerId }, select: { isModerator: true } }, _count: { select: { members: true, posts: true } }, posts: { where: { isDeleted: false, isDraft: false }, orderBy: { createdAt: "desc" }, take: 12, include: { author: { select: { displayName: true, username: true } }, _count: { select: { replies: true } } }, }, } });
  if (!space) notFound(); const joined = space.members.length > 0;
  return <main id="main-content" tabIndex={-1} className="app-shell"><ProductNav/><section className="surface-section space-detail"><header className="space-detail-header"><p className="eyebrow">{space.isFeatured ? "Featured Space" : "Space"}</p><h1>{space.name}</h1><p>{space.description}</p><div className="space-detail-actions"><SpaceMembership slug={space.slug} initialJoined={joined} initialMembers={space._count.members}/><Link className="button-outline" href={`/feed?space=${space.slug}#composer`}>Start a conversation</Link></div><p className="help">{space._count.members} members · {space._count.posts} discussions{space.members[0]?.isModerator ? " · You moderate this Space" : ""}</p></header><div className="space-detail-grid"><section><h2>Recent discussions</h2>{space.posts.length ? <div className="space-post-list">{space.posts.map((post) => <article key={post.id} className="panel"><span className="badge">{post.type.toLowerCase()}</span><h3><Link href={`/posts/${post.id}`}>{post.title}</Link></h3><p>{post.body.slice(0, 220)}{post.body.length > 220 ? "…" : ""}</p><footer><Link href={`/people/${post.author.username}`}>{post.author.displayName}</Link><Link href={`/posts/${post.id}#replies`}>{post._count.replies} replies</Link></footer></article>)}</div> : <div className="panel"><h3>No discussions yet.</h3><p className="help">Start the first conversation in {space.name}.</p></div>}</section><aside className="space-detail-aside"><section className="panel"><h2>Rules</h2><p className="help">{space.rules || "Be constructive, share context, and respect other members."}</p></section><section className="panel"><h2>Topics</h2><div className="profile-tags">{space.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></section></aside></div></section></main>;
}
