import Image from "next/image";
import Link from "next/link";

const principles = [["Conversation", "Ask questions, share work, and learn with people across technology."], ["Knowledge", "Turn strong discussions into durable, attributed guides and research."], ["Trust", "Make sources, contributors, review status, and expertise visible."]];
const pathways = [["Community", "Join thoughtful discussions across AI, programming, web, data, design, and more.", "/feed", "Open discussions"], ["Knowledge", "Read and create guides, answers, research notes, benchmarks, and case studies.", "/knowledge", "Browse knowledge"], ["Explore", "Find public people, Spaces, discussions, replies, and verified knowledge.", "/explore", "Search Pnyx"], ["AI assistance", "Summarize public discussions, suggest tags, and draft from selected source material.", "/feed", "See the commons"]];

function Brand({ footer = false }: { footer?: boolean }) { return <Link className={footer ? "footer-brand" : "brand-lockup"} href="/" aria-label="Pnyx home"><Image src="/brand/pnyx-mark.svg" alt="" width={footer ? 32 : 42} height={footer ? 32 : 42} priority /><span>Pnyx</span></Link>; }

export default function HomePage() {
  return <main className="site-shell">
    <nav className="topbar" aria-label="Primary navigation"><Brand /><div className="nav-links"><a href="#principles">Why Pnyx</a><a href="#pathways">Explore</a><a href="#foundation">Foundation</a></div><Link className="nav-action" href="/feed">Enter the commons</Link></nav>
    <section className="hero" aria-labelledby="hero-title"><p className="eyebrow">A technology knowledge network</p><h1 id="hero-title">Where technology conversations become <em>organised knowledge.</em></h1><p className="hero-copy">Pnyx brings community, learning, research, and collaboration into one thoughtful home for people who build with technology.</p><div className="hero-actions"><Link className="button button-primary" href="/feed">Discover the commons</Link><a className="text-link" href="#pathways">See what belongs here <span aria-hidden="true">↓</span></a></div></section>
    <section className="principles" id="principles" aria-labelledby="principles-title"><div><p className="eyebrow">The compounding loop</p><h2 id="principles-title">Useful ideas should not disappear into history.</h2></div><div className="principle-grid">{principles.map(([title, body], index) => <article className="principle" key={title}><span className="principle-number">0{index + 1}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="pathways" id="pathways" aria-labelledby="pathways-title"><div className="pathways-heading"><p className="eyebrow">A home for the whole loop</p><h2 id="pathways-title">Start with a conversation. Leave with something useful.</h2></div><div className="pathway-grid">{pathways.map(([title, body, href, label]) => <article className="pathway-card" key={title}><span className="pathway-index" aria-hidden="true">✦</span><h3>{title}</h3><p>{body}</p><Link className="text-link" href={href}>{label} <span aria-hidden="true">→</span></Link></article>)}</div></section>
    <section className="foundation" id="foundation" aria-labelledby="foundation-title"><div className="foundation-copy"><p className="eyebrow">The foundation is ready</p><h2 id="foundation-title">A calm, durable base for the community ahead.</h2><p>Typed boundaries, PostgreSQL persistence, privacy-aware telemetry, structured operations, and accessible design are in place for the next product loop.</p><Link className="button button-primary inline-flex mt-6" href="/sign-up">Join Pnyx</Link></div><div className="status-card" aria-label="Foundation capabilities"><div className="status-heading"><span className="status-dot" aria-hidden="true" />Foundation status</div><ul><li>Next.js + TypeScript application</li><li>Prisma + PostgreSQL data model</li><li>Health checks and structured logs</li><li>Accessible responsive design system</li></ul></div></section>
    <footer><Brand footer /><span>Technology conversations, organised.</span></footer>
  </main>;
}