import Link from "next/link";
import { prisma } from "@/lib/prisma";

export async function ExploreDiscovery() {
  const [posts, spaces, artifacts] = await Promise.all([
    prisma.post.findMany({ where: { isDeleted: false, isDraft: false, visibility: "PUBLIC" }, select: { id: true, title: true, type: true, space: { select: { name: true, slug: true } }, _count: { select: { replies: true, reactions: true } } }, orderBy: [{ reactions: { _count: "desc" } }, { replies: { _count: "desc" } }, { createdAt: "desc" }], take: 5 }),
    prisma.space.findMany({ where: { isPublic: true }, select: { slug: true, name: true, description: true, tags: true, _count: { select: { members: true, posts: true } } }, orderBy: [{ members: { _count: "desc" } }, { posts: { _count: "desc" } }], take: 5 }),
    prisma.artifact.findMany({ where: { status: { in: ["PUBLISHED", "COMMUNITY_REVIEWED", "VERIFIED"] } }, select: { id: true, title: true, type: true, status: true, space: { select: { name: true } } }, orderBy: { updatedAt: "desc" }, take: 4 }),
  ]);
  return <section className="surface-section" aria-labelledby="discover-heading"><div className="section-heading"><div><p className="eyebrow">Discover</p><h2 id="discover-heading">What the commons is working on</h2></div><p>These lists use live activity, membership, and published knowledge—never demo rankings.</p></div><div className="grid gap-5 xl:grid-cols-3"><section className="panel"><h3>Trending discussions</h3>{posts.length?<ul className="space-y-4">{posts.map(post=><li key={post.id}><span className="badge">{post.type.toLowerCase()}</span><Link className="mt-2 block font-semibold" href={`/posts/${post.id}`}>{post.title}</Link><p className="help">{post.space.name} · {post._count.replies} replies · {post._count.reactions} reactions</p></li>)}</ul>:<p className="help">Discussions will appear here once the community starts responding.</p>}</section><section className="panel"><h3>Active Spaces</h3>{spaces.length?<ul className="space-y-4">{spaces.map(space=><li key={space.slug}><Link className="font-semibold" href={`/spaces/${space.slug}`}>{space.name}</Link><p className="help">{space.description}</p><p className="help">{space._count.members} members · {space._count.posts} discussions</p></li>)}</ul>:<p className="help">Public Spaces will appear here.</p>}</section><section className="panel"><h3>Recently updated knowledge</h3>{artifacts.length?<ul className="space-y-4">{artifacts.map(artifact=><li key={artifact.id}><span className="badge">{artifact.status.toLowerCase().replace("_"," ")}</span><Link className="mt-2 block font-semibold" href={`/knowledge/${artifact.id}`}>{artifact.title}</Link><p className="help">{artifact.space.name} · {artifact.type.toLowerCase()}</p></li>)}</ul>:<p className="help">Published knowledge will appear here.</p>}</section></div></section>;
}