"use client";

import { FormEvent, useEffect, useState } from "react";

type Profile = { username: string; avatarUrl: string | null; displayName: string; bio: string | null; timezone: string | null; expertise: string[] | null; links: string[] | null; profileVisibility: "PUBLIC" | "FOLLOWERS_ONLY" | "PRIVATE" };

export function ProfileEditor() {
  const [profile, setProfile] = useState<Profile | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/account/profile").then(async (response) => { if (!response.ok) throw new Error(); setProfile(await response.json()); }).catch(() => setError("Your profile could not be loaded.")); }, []);
  if (error) return <p role="alert" className="rounded-2xl bg-red-50 p-5 text-red-800">{error}</p>;
  if (!profile) return <p role="status" className="text-slate-600">Loading your profile…</p>;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); const data = new FormData(event.currentTarget); const payload = { displayName: data.get("displayName"), avatarUrl: data.get("avatarUrl") || null, bio: data.get("bio") || null, timezone: data.get("timezone") || null, expertise: String(data.get("expertise") || "").split(",").map((item) => item.trim()).filter(Boolean), links: String(data.get("links") || "").split("\n").map((item) => item.trim()).filter(Boolean), profileVisibility: data.get("profileVisibility") }; const response = await fetch("/api/account/profile", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) setError(result.error ?? "Profile could not be saved."); else { setProfile({ ...profile, ...result }); setMessage("Profile saved."); } setBusy(false); }
  return <form onSubmit={submit} className="grid max-w-2xl gap-5"><p className="text-sm text-slate-500">@{profile.username}</p><label className="grid gap-2 text-sm font-semibold text-[#0B1F3A]">Display name<input name="displayName" defaultValue={profile.displayName} required className="rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-blue-100" /></label><label className="grid gap-2 text-sm font-semibold text-[#0B1F3A]">Avatar URL<input name="avatarUrl" type="url" defaultValue={profile.avatarUrl ?? ""} className="rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-blue-100" /></label><label className="grid gap-2 text-sm font-semibold text-[#0B1F3A]">Bio<textarea name="bio" defaultValue={profile.bio ?? ""} rows={4} className="rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-blue-100" /></label><label className="grid gap-2 text-sm font-semibold text-[#0B1F3A]">Expertise <span className="font-normal text-slate-500">Comma-separated</span><input name="expertise" defaultValue={profile.expertise?.join(", ") ?? ""} className="rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-blue-100" /></label><label className="grid gap-2 text-sm font-semibold text-[#0B1F3A]">Links <span className="font-normal text-slate-500">One https URL per line</span><textarea name="links" defaultValue={profile.links?.join("\n") ?? ""} rows={3} className="rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-blue-100" /></label><label className="grid gap-2 text-sm font-semibold text-[#0B1F3A]">Profile visibility<select name="profileVisibility" defaultValue={profile.profileVisibility} className="rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal outline-none focus:border-[#2563EB] focus:ring-2 focus:ring-blue-100"><option value="PUBLIC">Public</option><option value="FOLLOWERS_ONLY">Followers only</option><option value="PRIVATE">Private</option></select></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message && <p role="status" className="rounded-xl bg-teal-50 p-3 text-sm text-teal-900">{message}</p>}<button disabled={busy} className="w-fit rounded-full bg-[#0B1F3A] px-5 py-3 font-bold text-white hover:bg-[#2563EB] disabled:opacity-60">{busy ? "Saving…" : "Save profile"}</button></form>;
}
