"use client";

import { useEffect, useState } from "react";

type Space = { id: string; slug: string; name: string; description: string; tags: string[]; isFeatured: boolean; _count: { members: number; followers: number } };

export function SpaceBrowser() {
  const [spaces, setSpaces] = useState<Space[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  useEffect(() => { fetch("/api/spaces").then(async (response) => { if (!response.ok) throw new Error(); setSpaces(await response.json()); }).catch(() => setError("Spaces could not be loaded right now.")); }, []);
  async function change(slug: string, action: "membership" | "follow", method: "POST" | "DELETE") { setBusy(`${action}:${slug}`); const response = await fetch(`/api/spaces/${slug}/${action}`, { method }); if (response.status === 401) window.location.assign(`/sign-in?returnTo=/spaces`); else if (response.ok) setSpaces((items) => items.map((space) => space.slug === slug ? { ...space, _count: { ...space._count, ...(action === "membership" ? { members: Math.max(0, space._count.members + (method === "POST" ? 1 : -1)) } : { followers: Math.max(0, space._count.followers + (method === "POST" ? 1 : -1)) }) } } : space)); setBusy(""); }
  if (error) return <p role="alert" className="rounded-2xl bg-red-50 p-5 text-red-800">{error}</p>;
  if (!spaces.length) return <p className="rounded-2xl border border-slate-200 bg-white p-8 text-slate-600">No public Spaces are available yet.</p>;
  return <div className="grid gap-4 md:grid-cols-2">{spaces.map((space) => <article key={space.id} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="mb-2 text-xs font-extrabold uppercase tracking-[.14em] text-[#2563EB]">{space.isFeatured ? "Featured Space" : "Space"}</p><h2 className="text-2xl font-bold tracking-[-.04em] text-[#0B1F3A]">{space.name}</h2></div><span aria-hidden="true" className="h-3 w-3 rounded-full bg-[#D4A017]" /></div><p className="min-h-16 leading-7 text-slate-600">{space.description}</p><div className="mt-5 flex flex-wrap gap-2">{space.tags.map((tag) => <span key={tag} className="rounded-full bg-[#F8FAFC] px-3 py-1 text-xs text-slate-600">{tag}</span>)}</div><div className="mt-6 flex items-center justify-between border-t border-slate-100 pt-4 text-sm text-slate-500"><span>{space._count.members} members · {space._count.followers} followers</span><div className="flex gap-2"><button disabled={busy.length > 0} onClick={() => change(space.slug, "follow", "POST")} className="rounded-full border border-slate-300 px-3 py-2 font-bold text-[#0B1F3A] hover:border-[#2563EB] hover:text-[#2563EB]">Follow</button><button disabled={busy.length > 0} onClick={() => change(space.slug, "membership", "POST")} className="rounded-full bg-[#0B1F3A] px-3 py-2 font-bold text-white hover:bg-[#2563EB]">Join</button></div></div></article>)}</div>;
}
